all:
	
	g++ -O2 -fopenmp timer.C mand_set_omp.cpp -o mand_omp
	g++ -O2 -fopenmp timer.C mand_set_omp_d.cpp -o mand_omp_d
	g++ -O2 -fopenmp timer.C mand_set_omp_g.cpp -o mand_omp_g
	g++ -O2 -fopenmp timer.C mand_set_omp_r.cpp -o mand_omp_r