all:
	
	g++ -O2 -fopenmp timer.C goldbach_omp_s.cpp -o goldbach_omp_s
	g++ -O2 -fopenmp timer.C goldbach_omp_d.cpp -o goldbach_omp_d
	g++ -O2 -fopenmp timer.C goldbach_omp_g.cpp -o goldbach_omp_g
	g++ -O2 -fopenmp timer.C goldbach_omp_r.cpp -o goldbach_omp_r


